apiVersion: apps/v1
kind: Deployment
metadata:
  name: word-to-pdf-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: word-to-pdf
  template:
    metadata:
      labels:
        app: word-to-pdf
    spec:
      containers:
      - name: word-to-pdf-container
        image: your-dockerhub-username/your-image-name # Replace with your Docker image name.
        ports:
        - containerPort: 5000 
---
apiVersion: v1
kind: Service
metadata:
  name: word-to-pdf-service
spec:
  type: LoadBalancer 
  ports:
  - port: 80 
    targetPort: 5000 
  selector:
    app: word-to-pdf
